const PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\n"+
"MIHOMA0GCSqGSIb3DQEBAQUAA4G8ADCBuAKBsACvECHAIfD201aWZGl3fk6YpdBb\n"+
"Ke7GfTDYhZvjJAkfc99g8qNBiG1tuUL9nGV+dP0GgL8hXYoALLAruR9YtArPcs1n\n"+
"/0MtpxRxvLXVx08havVsVFrZ2HIqr8WrBGgCoaWmx7OATYylg+JdKIb9upCCJbQu\n"+
"tAU37943I6RzZXIGGZQR/c4EiYLJIJotSZ/+7rAh/P2EXEnYmqQ37Xj7iNmkaSik\n"+
"qg+hjf55YTSVMZD1AgMBAAE=\n"+
"-----END PUBLIC KEY-----";

export default PUBLIC_KEY;